language: java
jdk: oraclejdk8
dist: trusty
install: true
addons:
  sonarcloud:
    organization: "markoniemi-github"
    token: $SONAR_CLOUD_TOKEN
script:
  mvn clean verify sonar:sonar deploy --settings settings.xml
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
